#ifndef DULCIFICUM_INCLUDE_DULCIFICUM_H
#define DULCIFICUM_INCLUDE_DULCIFICUM_H

#ifndef DULCIFICUM_VERSION
#define DULCIFICUM_VERSION "0.1.0"
#endif

// TODO: this will be the main API

#endif // DULCIFICUM_INCLUDE_DULCIFICUM_H
