name: lint-formatter

on:
  workflow_dispatch:

  push:
    paths:
      - 'include/**/*.h*'
      - 'src/**/*.cpp*'
      - 'tests/**/*.cpp*'
      - '.github/workflows/lint-formatter.yml'

jobs:
  lint-formatter-job:
    uses: ultimaker/cura-workflows/.github/workflows/apply-cpp-linter.yml@main
