name: conan-package

on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'test_package/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - 'pyDulcificum/**'
      - 'DulcificumJS/**'
      - '.github/workflows/conan-package.yml'
      - '.github/worflows/requirements-conan-package.txt'
    branches:
      - main
      - 'CURA-*'
      - 'NP-*'
      - 'PP-*'
      - 'SS-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]*'
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@main
    secrets: inherit
