name: lint-tidier

on:
  workflow_dispatch:

  pull_request:
    paths:
      - 'include/**/*.h*'
      - 'src/**/*.cpp*'
      - 'test/**/*.cpp*'

jobs:
  lint-tidier-job:
    name: Auto-apply clang-tidy
    uses: ultimaker/cura-workflows/.github/workflows/lint-tidier.yml@main
