---
name: unit-test
on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test.yml'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'SS-*'
      - '[0-9]+.[0-9]+'

  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test.yml'
    branches:
      - main
      - '[0-9]+.[0-9]+'

permissions:
  contents: read

env:
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_USER }}
  CONAN_PASSWORD: ${{ secrets.CONAN_PASS }}

jobs:
  conan-recipe-version:
    uses: ultimaker/cura-workflows/.github/workflows/conan-recipe-version.yml@CURA-10831
    with:
      project_name: dulcificum

  testing:
    uses: ultimaker/cura-workflows/.github/workflows/unit-test.yml@CURA-10831
    needs: [ conan-recipe-version ]
    with:
      recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
      conan_extra_args: '-c tools.build:skip_test=False'
      unit_test_cmd: 'ctest --output-junit unit_test.xml'
      unit_test_dir: 'build/Release'
      build: true