---
name: unit-test
on:
  push:
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test.yml'
    branches:
      - main
      - 'CURA-*'
      - 'PP-*'
      - 'SS-*'
      - '[0-9]+.[0-9]+'

  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test.yml'
      - '.github/workflows/unit-test-post.yml'
    branches:
      - main
      - '[0-9]+.[0-9]+'

jobs:
  testing:
    name: Run unit tests
# FIXME: use main once merged
    uses: ultimaker/cura-workflows/.github/workflows/unit-test.yml@CURA-11622_conan_v2
    with:
      test_use_ctest: true
